// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQA52fdTl0WCwbP8lBtTI4y-pRsjPscRk',
    appId: '1:27498611724:web:3406b55d35e2bf864e1a29',
    messagingSenderId: '27498611724',
    projectId: 'workflow-de4c0',
    authDomain: 'workflow-de4c0.firebaseapp.com',
    storageBucket: 'workflow-de4c0.firebasestorage.app',
    measurementId: 'G-QXK2CT2BNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUqB_T7GqOvoRJI1npTRqTeUWh66owOtM',
    appId: '1:27498611724:android:cc692fe00c074a544e1a29',
    messagingSenderId: '27498611724',
    projectId: 'workflow-de4c0',
    storageBucket: 'workflow-de4c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBAF-CMa0g_99HTmtMZNzMEm_M8jdfYws',
    appId: '1:27498611724:ios:ed0e2733800d2d8e4e1a29',
    messagingSenderId: '27498611724',
    projectId: 'workflow-de4c0',
    storageBucket: 'workflow-de4c0.firebasestorage.app',
    androidClientId: '27498611724-lridmoc64vkglf1cd82uvpkul9bqs2fs.apps.googleusercontent.com',
    iosClientId: '27498611724-rbdpdndn2ie3d7ch402omidluo7okn0e.apps.googleusercontent.com',
    iosBundleId: 'com.hourflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBAF-CMa0g_99HTmtMZNzMEm_M8jdfYws',
    appId: '1:27498611724:ios:ed0e2733800d2d8e4e1a29',
    messagingSenderId: '27498611724',
    projectId: 'workflow-de4c0',
    storageBucket: 'workflow-de4c0.firebasestorage.app',
    androidClientId: '27498611724-lridmoc64vkglf1cd82uvpkul9bqs2fs.apps.googleusercontent.com',
    iosClientId: '27498611724-rbdpdndn2ie3d7ch402omidluo7okn0e.apps.googleusercontent.com',
    iosBundleId: 'com.hourflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQA52fdTl0WCwbP8lBtTI4y-pRsjPscRk',
    appId: '1:27498611724:web:ba455a99f8094e704e1a29',
    messagingSenderId: '27498611724',
    projectId: 'workflow-de4c0',
    authDomain: 'workflow-de4c0.firebaseapp.com',
    storageBucket: 'workflow-de4c0.firebasestorage.app',
    measurementId: 'G-KBFVPKNN0L',
  );

}