import 'package:flutter/widgets.dart';
import 'package:provider/provider.dart';
import '../logic/viewmodels/settings_viewmodel.dart';

class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'English': {
      'dashboard': 'Dashboard',
      'calendar': 'Calendar',
      'history': 'Card',
      'settings': 'Settings',
      'today_log': 'Today\'s Log',
      'no_log_selected': 'No date selected',
      'am_in': 'AM IN',
      'am_out': 'AM OUT',
      'pm_in': 'PM IN',
      'pm_out': 'PM OUT',
      'ot_in': 'OT IN',
      'ot_out': 'OT OUT',
      'work_summary': 'Work Summary',
      'what_did_you_do': 'What did you accomplish today?',
      'save_log': 'Save Log',
      'saving': 'Saving...',
      'log_history': 'Log History',
      'log_summary': 'Log Summary',
      'no_logs_found': 'No logs found for this day.',
      'tasks': 'Tasks:',
      'time_card_grid': 'Card',
      'day': 'Day',
      'morning': 'AM',
      'afternoon': 'PM',
      'overtime': 'OT',
      'daily': 'Daily',
      'total': 'Total',
      'monthly_total': 'TOTAL MONTHLY ACCUMULATED TIME:',
      'preferences': 'Preferences',
      'notifications': 'Notifications',
      'dark_theme': 'Dark Theme',
      'language': 'Language',
      'push_notifications': 'Push Notifications',
      'daily_shift_reminders': 'Daily Shift Reminders',
      'sign_out': 'Sign Out',
      'select_language': 'Select Language',
      'delete_log': 'Delete Log',
      'delete_confirm': 'Are you sure you want to delete all logs for ',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'new_event': 'New Event',
      'event_title': 'Event Title',
      'event_desc': 'Event Description',
      'add': 'Add',
    },
    'Spanish': {
      'dashboard': 'Tablero',
      'calendar': 'Calendario',
      'history': 'Tarjeta',
      'settings': 'Configuración',
      'today_log': 'Registro de Hoy',
      'no_log_selected': 'Ninguna fecha seleccionada',
      'am_in': 'ENTRADA AM',
      'am_out': 'SALIDA AM',
      'pm_in': 'ENTRADA PM',
      'pm_out': 'SALIDA PM',
      'ot_in': 'ENTRADA HORAS EXTRA',
      'ot_out': 'SALIDA HORAS EXTRA',
      'work_summary': 'Resumen de Trabajo',
      'what_did_you_do': '¿Qué lograste hoy?',
      'save_log': 'Guardar Registro',
      'saving': 'Guardando...',
      'log_history': 'Historial de Registros',
      'log_summary': 'Resumen de Registros',
      'no_logs_found': 'No se encontraron registros para este día.',
      'tasks': 'Tareas:',
      'time_card_grid': 'Tarjeta',
      'day': 'Día',
      'morning': 'AM',
      'afternoon': 'PM',
      'overtime': 'OT',
      'daily': 'Diario',
      'total': 'Total',
      'monthly_total': 'TIEMPO TOTAL ACUMULADO MENSUAL:',
      'preferences': 'Preferencias',
      'notifications': 'Notificaciones',
      'dark_theme': 'Tema Oscuro',
      'language': 'Idioma',
      'push_notifications': 'Notificaciones Push',
      'daily_shift_reminders': 'Recordatorios Diarios',
      'sign_out': 'Cerrar Sesión',
      'select_language': 'Seleccionar Idioma',
      'delete_log': 'Eliminar Registro',
      'delete_confirm': '¿Estás seguro de que quieres eliminar los registros para ',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'new_event': 'Nuevo Evento',
      'event_title': 'Título del Evento',
      'event_desc': 'Descripción del Evento',
      'add': 'Añadir',
    },
    'Filipino': {
      'dashboard': 'Dashboard',
      'calendar': 'Kalendaryo',
      'history': 'Card',
      'settings': 'Mga Setting',
      'today_log': 'Log Ngayong Araw',
      'no_log_selected': 'Walang napiling petsa',
      'am_in': 'PASOK UMAGA',
      'am_out': 'LABAS UMAGA',
      'pm_in': 'PASOK HAPON',
      'pm_out': 'LABAS HAPON',
      'ot_in': 'PASOK OT',
      'ot_out': 'LABAS OT',
      'work_summary': 'Buod ng Trabaho',
      'what_did_you_do': 'Ano ang natapos mo ngayon?',
      'save_log': 'I-save ang Log',
      'saving': 'Nagse-save...',
      'log_history': 'Kasaysayan ng Log',
      'log_summary': 'Buod ng Log',
      'no_logs_found': 'Walang log sa araw na ito.',
      'tasks': 'Mga Gawain:',
      'time_card_grid': 'Card',
      'day': 'Araw',
      'morning': 'AM',
      'afternoon': 'PM',
      'overtime': 'OT',
      'daily': 'Araw-araw',
      'total': 'Kabuuan',
      'monthly_total': 'KABUUANG ORAS NA NAIPON SA BUWAN:',
      'preferences': 'Mga Kagustuhan',
      'notifications': 'Mga Notipikasyon',
      'dark_theme': 'Madilim na Tema',
      'language': 'Wika',
      'push_notifications': 'Mga Push Notipikasyon',
      'daily_shift_reminders': 'Pang-araw-araw na Paalala',
      'sign_out': 'Mag-Sign Out',
      'select_language': 'Pumili ng Wika',
      'delete_log': 'Burahin ang Log',
      'delete_confirm': 'Sigurado ka bang gusto mong burahin ang log para sa ',
      'cancel': 'Kanselahin',
      'delete': 'Burahin',
      'new_event': 'Bagong Kaganapan',
      'event_title': 'Pamagat ng Kaganapan',
      'event_desc': 'Paglalarawan ng Kaganapan',
      'add': 'Idagdag',
    }
  };

  static String tr(BuildContext context, String key) {
    final lang = Provider.of<SettingsViewModel>(context).selectedLanguage;
    final dict = _localizedValues[lang] ?? _localizedValues['English']!;
    return dict[key] ?? key;
  }
}

extension LocalizationExtension on BuildContext {
  String tr(String key) => AppLocalizations.tr(this, key);
}
